### ISSUE TITLE
This project is temporarily paused

### ISSUE THREAD

**Issue by willnode** [willnode/forward-domain#1]
To run this project one has to preserve a whole IP address to run this service so it's kinda expensive and it seems that interest in this project is none.

Still, this is a fun project for me, I thought myself how to create an automatic SSL signing with LE. Definitely useful for my next project.

**Comment by DaGaMs** [comment]
ha, shame! I was actually just trying to use this ;-)

**Comment by willnode** [comment]
I hate to say this but spending for nothing is something I couldn't afford 😂 probably 10 stars in this project and I will reconsider to get this project back up and running.

**Comment by DaGaMs** [comment]
😅 Fair enough - I admit that I ended up resorting to https://freedirector.io/

**Comment by DaGaMs** [comment]
Not as good as your solution though - no https:// redirects. So you see, there might be a market for your system!

**Comment by willnode** [comment]
Whoa, ok. That's give me a little bit of reason 😅 I'll try to repurpose one of my existing VM for this project.

**Comment by willnode** [comment]
This service is now back online with [some improvements](https://github.com/willnode/forward-domain/blob/main/CHANGES.md)! 🔥

**Comment by martin-braun** [comment]
@willnode Here is your 10th star, I actually use your service. Add GitHub Sponsoring (with custom amount) and I might sponsor a tiny bit to compensate a little cost. You don't need a static IP if you use CNAME entries, something that you should show instead, see https://blog.wellosoft.net/how-to-redirect-a-domain-only-using-dns-records.

@DaGaMs This is proprietary stuff, but here you have honest open-source work. I'd rather Sponsor this project and use it instead of relying on big closed source cooperations. You cannot validate their code, they probably track you, perhaps they sell your data and they are often target of data breaches, because nobody can audit their code, except for them themselves.

**Comment by willnode** [comment]
Thanks for your kind words (and star) @martin-braun.

I have a separate static IP just in case people are still stuck with traditional hosting domains, I don't want them forced to use Cloudflare just to use this service at an apex domain (_unless they also want IPv6_). But another static IP is free anyway so I don't bother with it currently.

This service serves hundreds of domains already but I don't struggle currently as this service is part of my operation at @domcloud and it generates revenue (to cover hosting costs only, because it's also in development, lol). But anyway someone already donating a year's worth of this service hosting costs so I'm forever grateful for that.

**Comment by WhiteBlackGoose** [comment]
Thank you, amazing!
