### ISSUE TITLE
Issue 'CAA record is not "letsencrypt.org"'

### ISSUE THREAD

**Issue by FyrusOP** [willnode/forward-domain#11]
Hi,

First off thanks for providing such a service.

It seems that for every domain I implement the redirect the 'www' comes back with "CAA record is not "letsencrypt.org""

Is this a known issue or are we looking in the wrong direction for this issue?

**Comment by willnode** [comment]
We're [recently introduced](https://github.com/willnode/forward-domain/commit/c53305ca68abd283493fc5f7cb55521d5d42c547) this warning because some people apparently set CAA to other than that, preventing let's encrypt from successfully validating the domain.

Try removing CAA record in your domain, or let me know your domain (either here or email) for me to check.

**Comment by FyrusOP** [comment]
Dear Will,

I am trying to fix this for the *bfohd.de <http://bfohd.de> *domain. There
should be no CAA records present.



Op vr 12 apr 2024 om 10:29 schreef Wildan M ***@***.***>:

**Comment by willnode** [comment]
[Fixed](https://github.com/willnode/forward-domain/commit/0a355e9b0ee3844e8bda7a705c9a630586580be8). Thank you for reporting.
