### ISSUE TITLE
[Request] IPv6

### ISSUE THREAD

**Issue by Redjard** [willnode/forward-domain#2]
Just saw IPv6 got dropped in the major change, is there any chance to get it back?

This project fills an incredibly usefull niche for me, as I work with clients that host at providers chargin for ssl certs.
This means for their alias domains they would have to pay 1€/month/domain for the privilege of a simple https redirect which would barely get used.
I would gladly pay for the v4 and v6 IP of this service, if only to get back at those scummy webhosters.

The redirect using this service is already better than anything I've found elsewhere, but considering the webhoster fully supports IPv6 for the websites, it just doesn't feel right to only do IPv4 redirects.

**Comment by willnode** [comment]
I realized I haven't added AAAA records for `r.forwarddomain.net`. I just fixed that.

It was dropped because the host server I use (Digital Ocean) doesn't support IPv6 floating IPs, so there's no guarantee it will be the same over time.

Anyway, If you want to add an IPv6 record for apex domain redirect, you can get the [up-to-date address from nslookup](https://dns.google/query?name=r.forwarddomain.net&rr_type=AAAA&ecs=). If you do subdomain redirection, keep using CNAME, as it already works with IPv6 from now.

**Comment by Redjard** [comment]
Thanks, I ended up changing my dns hosting provider from dynu to cloudflare, because cloudflare has virtual CNAME wich will essentially do that nslookup without another script as an additional point of failure. Kinda a shame most DNS hosters don't have vCNAME/ANAME/ALIAS records, those simplify this problem a lot.

**Comment by willnode** [comment]
Yeah, [CNAME flattening](https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/) is very useful indeed. 

Just pointing out for future readers.
